def raise_exception():
    print("Exception raised")

    